package com.example.llama.domain.model;

public enum AgentType {
    ANALYST,
    STRATEGIST,
    CODER,

    SCOUT,
    QUERY_SPECIALIST,
    KNOWLEDGE_SELECTOR,
    KNOWLEDGE_DISTILLER,

    // Planning TF (Architects)
    LOGIC_ARCHITECT,
    BOUNDARY_ARCHITECT,
    ENUM_ARCHITECT,
    CONCURRENCY_ARCHITECT,
    INTEGRITY_ARCHITECT,
    MASTER_ARCHITECT,

    // Execution TF (Clerks & Managers)
    SETUP_CLERK,
    DATA_CLERK, DATA_MANAGER,
    MOCK_CLERK, MOCK_MANAGER,
    EXEC_CLERK, EXEC_MANAGER,
    VERIFY_CLERK, VERIFY_MANAGER,
    SERVICE_LOGIC_CLERK,
    SERVICE_BOUNDARY_CLERK,
    SERVICE_ANALYST,
    SERVICE_STRATEGIST,
    SERVICE_CODER,

    // Controller Domain
    CONTROLLER_ANALYST,
    CONTROLLER_STRATEGIST,
    CONTROLLER_CODER,

    // Repository Domain
    REPOSITORY_ANALYST,
    REPOSITORY_STRATEGIST,
    REPOSITORY_CODER,

    // Maintenance
    REPAIR_AGENT,

    // Assembly & Integration
    ASSEMBLY_CLERK, ASSEMBLY_MANAGER,
    IMPORT_CLERK,
    INTEGRATION_ARCHITECT,
    FRAGMENT_CLERK,
    FRAGMENT_PURIFIER,
    FORMAT_CLERK,
    ARBITRATOR,
    DIRECTOR,
    ANNOTATION_SCOUT,
    STRUCTURE_ANALYST,
    JUDGE,
    REPAIR_SPECIALIST
}
