/**
 * Generated by Test-Hae-Llama
 * Tool: Gemini CLI
 * Model: gemini-2.5-flash
 */


/**
 * Generated by Test-Hae-Llama
 * Tool: Gemini CLI
 * Model: gemini-2.5-flash
 */
package com.example.demo.presentation;

import com.example.demo.HelloController;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.extension.ExtendWith;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.restdocs.AutoConfigureRestDocs;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.web.context.WebApplicationContext;
import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.document;
import static org.springframework.restdocs.mockmvc.MockMvcRestDocumentation.documentationConfiguration;
import org.springframework.restdocs.RestDocumentationContextProvider;
import org.springframework.restdocs.RestDocumentationExtension;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@WebMvcTest(HelloController.class)
@AutoConfigureRestDocs
@ExtendWith({ RestDocumentationExtension.class, SpringExtension.class })
@DisplayName("HelloController 테스트")
class HelloControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private WebApplicationContext webApplicationContext;

    @BeforeEach
    void setUp(RestDocumentationContextProvider restDocumentation) {
        this.mockMvc = MockMvcBuilders.webAppContextSetup(webApplicationContext).apply(documentationConfiguration(restDocumentation)).build();
    }

    @Nested
    @DisplayName("hello 메서드는")
    class Describe_hello {

        @Nested
        @DisplayName("요청 파라미터가 없을 때")
        class Context_without_request_param {

            @DisplayName("기본 이름 'Llama'로 'Hello, Llama!'를 반환한다")
            @ParameterizedTest
            @CsvSource({ "Llama, Hello, Llama!" })
            void it_returns_hello_llama_with_default_name(String inputName, String expectedGreeting) throws Exception {
                // given
                String url = "/hello";
                // when
                mockMvc.perform(get(url)).andExpect(status().isOk()).andExpect(content().string(expectedGreeting)).andDo(document("hello/default-name"));
                // then (handled by andExpect)
            }
        }

        @Nested
        @DisplayName("요청 파라미터가 있을 때")
        class Context_with_request_param {

            @DisplayName("입력된 이름으로 'Hello, {name}!'을 반환한다")
            @ParameterizedTest
            @CsvSource({ "Spring, Hello, Spring!", "World, Hello, World!" })
            void it_returns_hello_with_given_name(String inputName, String expectedGreeting) throws Exception {
                // given
                String url = "/hello?name=" + inputName;
                // when
                mockMvc.perform(get(url)).andExpect(status().isOk()).andExpect(content().string(expectedGreeting)).andDo(document("hello/given-name"));
                // then (handled by andExpect)
            }
        }
    }
}
