/**
 * Generated by Test-Hae-Llama
 * Tool: Gemini CLI
 * Model: gemini-2.5-flash
 */
/**
 * Generated by Test-Hae-Llama
 * Tool: Gemini CLI
 * Model: gemini-2.5-flash
 */
package com.example.demo;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.test.web.servlet.MockMvc;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Generated by Test-Hae-Llama
 * Tool: Gemini CLI
 * Model: gemini-2.5-flash
 */
@WebMvcTest(HelloController.class)
public class HelloControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Nested
    @DisplayName("Describe: GET /hello")
    class Describe_hello {

        @Test
        @DisplayName("Context: should return 'Hello, Llama!'")
        void it_returns_hello_llama() throws Exception {
            // given
            // when
            // then
            mockMvc.perform(get("/hello")).andExpect(status().isOk()).andExpect(content().string("Hello, Llama!"));
        }
    }
}