/**
 * Generated by Test-Hae-Llama
 * Tool: Gemini CLI
 * Model: gemini-2.5-flash
 */
/**
 * Generated by Test-Hae-Llama
 * Tool: Gemini CLI
 * Model: gemini-2.5-flash
 */
package com.example.demo.client;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.InjectMocks;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import static org.assertj.core.api.Assertions.assertThat;

@ExtendWith(MockitoExtension.class)
// FIXME: This test class should be renamed to ExchangeRateClientTest.
// The task instruction specifically requested to modify 'EmailClientTest.java'
// for 'ExchangeRateClient' methods.
class EmailClientTest {

    @InjectMocks
    private ExchangeRateClient exchangeRateClient;

    @BeforeEach
    void setUp() {
        // Common setup for mocks or test environment.
        // No specific setup needed for this simple method under test.
    }

    @Nested
    @DisplayName("getExchangeRate 메서드 테스트")
    class Describe_getExchangeRate {

        @Test
        @DisplayName("환율 조회 성공: 1300.0을 반환한다")
        void itReturnsDefaultExchangeRate() {
            // given

            // when
            double result = exchangeRateClient.getExchangeRate();

            // then
            assertThat(result).isEqualTo(1300.0);
        }
    }
}